name: designstudio
favicon: null
layout_spectrum: 0.004766769940033555
typography_spectrum: 0.05952706327661872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.22871380345895886
  lightness: 0.454497373662889
  saturation: 0.3919982095248997
  rhythmicContrast: 0.5791030032560229
purpose: []
